/*
[ * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nl.windesheim.kbsm2.opc01.asrs;

import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;

/**
 *
 * @author vanDijk
 */
public class OrderlijstDialoog extends javax.swing.JDialog {
	DatabaseCon con = new DatabaseCon();
    /**
     * Creates new form OrderlijstDialoog
     * @throws SQLException 
     * @throws IllegalAccessException 
     * @throws InstantiationException 
     * @throws ClassNotFoundException 
     */
    public OrderlijstDialoog(java.awt.Frame parent, boolean modal) throws ClassNotFoundException, InstantiationException, IllegalAccessException, SQLException {
        super(parent, modal);
        
        initComponents();

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * @throws SQLException 
     * @throws IllegalAccessException 
     * @throws InstantiationException 
     * @throws ClassNotFoundException 
     */
    @SuppressWarnings({ "unchecked", "rawtypes" })
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() throws ClassNotFoundException, InstantiationException, IllegalAccessException, SQLException {

        jlOrderlijst = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlistOrderlijst = new javax.swing.JList();
        jbSelecteer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Orderlijst");

        jlOrderlijst.setText("Orderlijst");
        
        ResultSet rs = con.getOrders();
       
        ArrayList<String> strings = new ArrayList<>();
        while(rs.next()){
        	String content = Integer.toString(rs.getInt("orderid"));
        	strings.add(content);
        	System.out.println(content);
        }

        jlistOrderlijst.setModel(new javax.swing.AbstractListModel() {
            /**
			 * 
			 */
			private static final long serialVersionUID = 7079733320920777194L;
			public int getSize(){ return strings.size(); }
            public Object getElementAt(int i) { return strings.get(i); }
        });
        jScrollPane1.setViewportView(jlistOrderlijst);

        jbSelecteer.setText("Selecteren");
        jbSelecteer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSelecteerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jbSelecteer))
                    .addComponent(jlOrderlijst))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlOrderlijst)
                .addGap(4, 4, 4)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbSelecteer)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSelecteerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSelecteerActionPerformed
        
    	String Selected = (String) this.jlistOrderlijst.getSelectedValue() ;
    	Paneel.JLOrderNr.setText(Selected);
        Paneel.BTPakbon.setEnabled(true);
    	this.dispose();
    	
    }//GEN-LAST:event_jbSelecteerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderlijstDialoog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderlijstDialoog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderlijstDialoog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderlijstDialoog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
				try {
					OrderlijstDialoog dialog;
					dialog = new OrderlijstDialoog(new javax.swing.JFrame(), true);
					dialog.addWindowListener(new java.awt.event.WindowAdapter() {
	                @Override
	                public void windowClosing(java.awt.event.WindowEvent e) {
	                        System.exit(0);
	                    }
	                });
	                dialog.setVisible(true);
					
				} catch (HeadlessException | ClassNotFoundException
						| InstantiationException | IllegalAccessException
						| SQLException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}


				}
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbSelecteer;
    private javax.swing.JLabel jlOrderlijst;
    private javax.swing.JList jlistOrderlijst;
    // End of variables declaration//GEN-END:variables
}
